#Hugo configuration
title = "aetaet"
baseURL = "https:\/\/aet.asdf.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758854"
subfolder = ""
